name: Lint Python Code

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    name: Lint Python Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install linters and formatters
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black autoflake

    - name: Remove unused imports and variables
      run: |
        autoflake . --in-place --remove-all-unused-imports --remove-unused-variables --recursive

    - name: Format code with Black
      run: |
        black .

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

